---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# ejoints

The goal of ejoints is to work with empirical joint distributions. 

## Installation

You can install ejoints from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("AnthonyEbert/ejoints")
```

## Example

```{r, basic}
library(ejoints)


# Suppose we have the following 2D data points 

input <- matrix(
  c(1, 1, 2, 2, 2, 2.1, 5, 5, 3, 2, 10, 3), 
  ncol = 2, 
  byrow = TRUE
)

input


# Sample 5 values from this empirical density

rejoint(5, input = input)

# Compute empirical density at some point 4, 5

dejoint(c(4,5), input = input)
```

Let's use ggplot2 to create a plot

```{r, plots}

library(dplyr)
library(ggplot2)

x = seq(-10, 15, by = 0.25)
input_df <- dplyr::as_data_frame(expand.grid(x,x))
input_df$z = apply(input_df, 1, dejoint, input = input)

ggplot(input_df) + aes(x = Var1, y = Var2, z = z) + geom_contour()

ggplot(input_df) + aes(x = Var1, y = Var2, fill = z) + geom_raster()

```


